begin;
create extension if not exists pgtap with schema extensions;
select extensions.plan(12);
select extensions.ok(not has_function_privilege('anon', 'public.start_night_with_bottle(uuid,text,timestamptz,text,jsonb,jsonb,jsonb)', 'EXECUTE'), 'anonymous users cannot start a bottle night');
insert into auth.users(id, email, raw_user_meta_data) values
 ('cd100000-0000-4000-8000-000000000001', 'mobile-recovery@example.test', '{"display_name":"Host","age_confirmed":true}');
create temporary table recovery_state(key text primary key, value jsonb);
grant all on recovery_state to authenticated;
create function pg_temp.recovery_id(text) returns uuid language sql as $$select (value #>> '{}')::uuid from recovery_state where key=$1$$;
create function pg_temp.recovery_bottle() returns jsonb language sql as $$select '{"id":"cd200000-0000-4000-8000-000000000001","label":"Gin","category":"spirit","volumeMl":750,"abvPercent":40,"pourMl":30,"defaultQuantity":2,"access":"everyone","allowedMemberIds":[]}'::jsonb$$;
select set_config('request.jwt.claim.sub', 'cd100000-0000-4000-8000-000000000001', true);
select set_config('request.jwt.claim.role', 'authenticated', true);
set local role authenticated;
select extensions.throws_ok($$select public.start_night_with_bottle('cd300000-0000-4000-8000-000000000099','Invalid bottle',clock_timestamp()+interval '2 hours','UTC','[]','[]',pg_temp.recovery_bottle() || '{"pourMl":751}'::jsonb)$$,'23514',null,'invalid bottle setup rolls back the whole start');
select extensions.is((select count(*) from public.nights where title='Invalid bottle'),0::bigint,'an invalid bottle does not leave a partial night');
insert into recovery_state values ('start', public.start_night_with_bottle('cd300000-0000-4000-8000-000000000001','Recovered bottle',clock_timestamp()+interval '2 hours','UTC','[]','[]',pg_temp.recovery_bottle()));
insert into recovery_state select 'night', value->'nightId' from recovery_state where key='start';
insert into recovery_state select 'host',to_jsonb(id) from public.night_members where night_id=pg_temp.recovery_id('night') and user_id=auth.uid();
select extensions.is((select value->>'duplicate' from recovery_state where key='start'),'false','a fresh start is created once');
select public.plan_shared_bottle('cd200000-0000-4000-8000-000000000001',pg_temp.recovery_id('host'),3,30,1,'cd300000-0000-4000-8000-000000000002',true) is not null;
insert into recovery_state select 'plan',to_jsonb(id) from public.drink_plan_items where night_member_id=pg_temp.recovery_id('host') and archived_at is null;
select extensions.is(public.log_drink(pg_temp.recovery_id('host'),pg_temp.recovery_id('plan'),null,clock_timestamp(),'cd300000-0000-4000-8000-000000000003',false,false)->>'status','created','the bottle plan logs a real serving');
insert into recovery_state values ('replay',public.start_night_with_bottle('cd300000-0000-4000-8000-000000000001','Old request',clock_timestamp()-interval '1 hour','UTC','[]','[]',pg_temp.recovery_bottle()));
select extensions.is((select value->>'duplicate' from recovery_state where key='replay'),'true','a start response lost until after its planned end is recoverable');
select extensions.is((select value->>'nightId' from recovery_state where key='replay'),pg_temp.recovery_id('night')::text,'recovery returns the original night');
select extensions.is((select planned_quantity from public.drink_plan_items where id=pg_temp.recovery_id('plan')),3,'recovery preserves later plan adjustments');
select extensions.is((public.get_night_snapshot(pg_temp.recovery_id('night'))->'sharedBottles'->0->>'remainingMl')::numeric,720::numeric,'recovery preserves the poured bottle volume');
select public.end_night(pg_temp.recovery_id('night')) is not null;
insert into recovery_state values ('ended', public.start_night_with_bottle('cd300000-0000-4000-8000-000000000001','Old request',clock_timestamp()-interval '1 hour','UTC','[]','[]',pg_temp.recovery_bottle() || '{"id":"cd200000-0000-4000-8000-000000000009"}'::jsonb));
select extensions.is((select value#>>'{snapshot,night,status}' from recovery_state where key='ended'),'ended','recovery returns the current ended state');
select extensions.is((select count(*) from public.shared_bottles where night_id=pg_temp.recovery_id('night')),1::bigint,'replays do not create extra bottles');
select extensions.is((select count(*) from public.drink_logs where night_member_id=pg_temp.recovery_id('host') and deleted_at is null),1::bigint,'recovery preserves logged drinks');
select * from extensions.finish();
rollback;
